// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/submitRsvp.ts";
import * as $$$$$$$$$$$0 from "./apps/decohub.ts";
import * as $$$$$$$$$$$1 from "./apps/site.ts";
import * as $$$1 from "./loaders/availableIcons.ts";
import * as $$$2 from "./loaders/icons.ts";
import * as $$$0 from "./loaders/List/Sections.tsx";
import * as $$$$$$0 from "./sections/Animation/Animation.tsx";
import * as $$$$$$1 from "./sections/Cards/IconCardsCarousel.tsx";
import * as $$$$$$2 from "./sections/Cards/IconCardsCarouselWithImage.tsx";
import * as $$$$$$3 from "./sections/Cards/ImageCardsCarousel.tsx";
import * as $$$$$$4 from "./sections/Cards/ImageCardsCarouselWithImage.tsx";
import * as $$$$$$5 from "./sections/Category/CategoryBanner.tsx";
import * as $$$$$$6 from "./sections/Category/CategoryGrid.tsx";
import * as $$$$$$7 from "./sections/Category/CategoryList.tsx";
import * as $$$$$$8 from "./sections/Content/AgendaSection.tsx";
import * as $$$$$$9 from "./sections/Content/Benefits.tsx";
import * as $$$$$$10 from "./sections/Content/BlogPosts.tsx";
import * as $$$$$$11 from "./sections/Content/CallToAction.tsx";
import * as $$$$$$12 from "./sections/Content/CardsCarousel.tsx";
import * as $$$$$$13 from "./sections/Content/CostumerPains.tsx";
import * as $$$$$$14 from "./sections/Content/CustomerStories.tsx";
import * as $$$$$$15 from "./sections/Content/Faq.tsx";
import * as $$$$$$16 from "./sections/Content/Features.tsx";
import * as $$$$$$17 from "./sections/Content/Hero.tsx";
import * as $$$$$$18 from "./sections/Content/Intro.tsx";
import * as $$$$$$19 from "./sections/Content/Logos.tsx";
import * as $$$$$$20 from "./sections/Content/Partners.tsx";
import * as $$$$$$21 from "./sections/Content/Pillars.tsx";
import * as $$$$$$22 from "./sections/Content/PromoVideo.tsx";
import * as $$$$$$23 from "./sections/Content/RichText.tsx";
import * as $$$$$$24 from "./sections/Content/Table.tsx";
import * as $$$$$$25 from "./sections/Content/Testimonials.tsx";
import * as $$$$$$26 from "./sections/Content/TextSection.tsx";
import * as $$$$$$27 from "./sections/Content/TextWithImage.tsx";
import * as $$$$$$28 from "./sections/Content/VideoSection.tsx";
import * as $$$$$$29 from "./sections/Footer/Footer.tsx";
import * as $$$$$$30 from "./sections/Gallery.tsx";
import * as $$$$$$31 from "./sections/Header/Header.tsx";
import * as $$$$$$32 from "./sections/Hero/HeroProgram.tsx";
import * as $$$$$$33 from "./sections/Images/BannerGrid.tsx";
import * as $$$$$$34 from "./sections/Images/Carousel.tsx";
import * as $$$$$$35 from "./sections/Images/ImageGallery.tsx";
import * as $$$$$$36 from "./sections/Images/ShoppableBanner.tsx";
import * as $$$$$$37 from "./sections/Landing/Agenda.tsx";
import * as $$$$$$38 from "./sections/Landing/Footer.tsx";
import * as $$$$$$39 from "./sections/Landing/HeroLanding.tsx";
import * as $$$$$$40 from "./sections/Landing/Mentors.tsx";
import * as $$$$$$41 from "./sections/Landing/Participants.tsx";
import * as $$$$$$42 from "./sections/Landing/SpaceCarousel.tsx";
import * as $$$$$$43 from "./sections/Landing/Sponsors.tsx";
import * as $$$$$$44 from "./sections/Layout/Container.tsx";
import * as $$$$$$45 from "./sections/Layout/Flex.tsx";
import * as $$$$$$46 from "./sections/Layout/Grid.tsx";
import * as $$$$$$47 from "./sections/Layout/GridItem.tsx";
import * as $$$$$$48 from "./sections/Links/LinkTree.tsx";
import * as $$$$$$49 from "./sections/Links/Shortcuts.tsx";
import * as $$$$$$50 from "./sections/Miscellaneous/CampaignTimer.tsx";
import * as $$$$$$51 from "./sections/Miscellaneous/CookieConsent.tsx";
import * as $$$$$$52 from "./sections/Miscellaneous/DoubleSlider.tsx";
import * as $$$$$$53 from "./sections/Miscellaneous/Slide.tsx";
import * as $$$$$$54 from "./sections/Newsletter/Newsletter.tsx";
import * as $$$$$$55 from "./sections/Social/InstagramPosts.tsx";
import * as $$$$$$56 from "./sections/Social/WhatsApp.tsx";
import * as $$$$$$57 from "./sections/Theme/Theme.tsx";

const manifest = {
  "loaders": {
    "deco-sites/mira-site/loaders/availableIcons.ts": $$$1,
    "deco-sites/mira-site/loaders/icons.ts": $$$2,
    "deco-sites/mira-site/loaders/List/Sections.tsx": $$$0,
  },
  "sections": {
    "deco-sites/mira-site/sections/Animation/Animation.tsx": $$$$$$0,
    "deco-sites/mira-site/sections/Cards/IconCardsCarousel.tsx": $$$$$$1,
    "deco-sites/mira-site/sections/Cards/IconCardsCarouselWithImage.tsx":
      $$$$$$2,
    "deco-sites/mira-site/sections/Cards/ImageCardsCarousel.tsx": $$$$$$3,
    "deco-sites/mira-site/sections/Cards/ImageCardsCarouselWithImage.tsx":
      $$$$$$4,
    "deco-sites/mira-site/sections/Category/CategoryBanner.tsx": $$$$$$5,
    "deco-sites/mira-site/sections/Category/CategoryGrid.tsx": $$$$$$6,
    "deco-sites/mira-site/sections/Category/CategoryList.tsx": $$$$$$7,
    "deco-sites/mira-site/sections/Content/AgendaSection.tsx": $$$$$$8,
    "deco-sites/mira-site/sections/Content/Benefits.tsx": $$$$$$9,
    "deco-sites/mira-site/sections/Content/BlogPosts.tsx": $$$$$$10,
    "deco-sites/mira-site/sections/Content/CallToAction.tsx": $$$$$$11,
    "deco-sites/mira-site/sections/Content/CardsCarousel.tsx": $$$$$$12,
    "deco-sites/mira-site/sections/Content/CostumerPains.tsx": $$$$$$13,
    "deco-sites/mira-site/sections/Content/CustomerStories.tsx": $$$$$$14,
    "deco-sites/mira-site/sections/Content/Faq.tsx": $$$$$$15,
    "deco-sites/mira-site/sections/Content/Features.tsx": $$$$$$16,
    "deco-sites/mira-site/sections/Content/Hero.tsx": $$$$$$17,
    "deco-sites/mira-site/sections/Content/Intro.tsx": $$$$$$18,
    "deco-sites/mira-site/sections/Content/Logos.tsx": $$$$$$19,
    "deco-sites/mira-site/sections/Content/Partners.tsx": $$$$$$20,
    "deco-sites/mira-site/sections/Content/Pillars.tsx": $$$$$$21,
    "deco-sites/mira-site/sections/Content/PromoVideo.tsx": $$$$$$22,
    "deco-sites/mira-site/sections/Content/RichText.tsx": $$$$$$23,
    "deco-sites/mira-site/sections/Content/Table.tsx": $$$$$$24,
    "deco-sites/mira-site/sections/Content/Testimonials.tsx": $$$$$$25,
    "deco-sites/mira-site/sections/Content/TextSection.tsx": $$$$$$26,
    "deco-sites/mira-site/sections/Content/TextWithImage.tsx": $$$$$$27,
    "deco-sites/mira-site/sections/Content/VideoSection.tsx": $$$$$$28,
    "deco-sites/mira-site/sections/Footer/Footer.tsx": $$$$$$29,
    "deco-sites/mira-site/sections/Gallery.tsx": $$$$$$30,
    "deco-sites/mira-site/sections/Header/Header.tsx": $$$$$$31,
    "deco-sites/mira-site/sections/Hero/HeroProgram.tsx": $$$$$$32,
    "deco-sites/mira-site/sections/Images/BannerGrid.tsx": $$$$$$33,
    "deco-sites/mira-site/sections/Images/Carousel.tsx": $$$$$$34,
    "deco-sites/mira-site/sections/Images/ImageGallery.tsx": $$$$$$35,
    "deco-sites/mira-site/sections/Images/ShoppableBanner.tsx": $$$$$$36,
    "deco-sites/mira-site/sections/Landing/Agenda.tsx": $$$$$$37,
    "deco-sites/mira-site/sections/Landing/Footer.tsx": $$$$$$38,
    "deco-sites/mira-site/sections/Landing/HeroLanding.tsx": $$$$$$39,
    "deco-sites/mira-site/sections/Landing/Mentors.tsx": $$$$$$40,
    "deco-sites/mira-site/sections/Landing/Participants.tsx": $$$$$$41,
    "deco-sites/mira-site/sections/Landing/SpaceCarousel.tsx": $$$$$$42,
    "deco-sites/mira-site/sections/Landing/Sponsors.tsx": $$$$$$43,
    "deco-sites/mira-site/sections/Layout/Container.tsx": $$$$$$44,
    "deco-sites/mira-site/sections/Layout/Flex.tsx": $$$$$$45,
    "deco-sites/mira-site/sections/Layout/Grid.tsx": $$$$$$46,
    "deco-sites/mira-site/sections/Layout/GridItem.tsx": $$$$$$47,
    "deco-sites/mira-site/sections/Links/LinkTree.tsx": $$$$$$48,
    "deco-sites/mira-site/sections/Links/Shortcuts.tsx": $$$$$$49,
    "deco-sites/mira-site/sections/Miscellaneous/CampaignTimer.tsx": $$$$$$50,
    "deco-sites/mira-site/sections/Miscellaneous/CookieConsent.tsx": $$$$$$51,
    "deco-sites/mira-site/sections/Miscellaneous/DoubleSlider.tsx": $$$$$$52,
    "deco-sites/mira-site/sections/Miscellaneous/Slide.tsx": $$$$$$53,
    "deco-sites/mira-site/sections/Newsletter/Newsletter.tsx": $$$$$$54,
    "deco-sites/mira-site/sections/Social/InstagramPosts.tsx": $$$$$$55,
    "deco-sites/mira-site/sections/Social/WhatsApp.tsx": $$$$$$56,
    "deco-sites/mira-site/sections/Theme/Theme.tsx": $$$$$$57,
  },
  "actions": {
    "deco-sites/mira-site/actions/submitRsvp.ts": $$$$$$$$$0,
  },
  "apps": {
    "deco-sites/mira-site/apps/decohub.ts": $$$$$$$$$$$0,
    "deco-sites/mira-site/apps/site.ts": $$$$$$$$$$$1,
  },
  "name": "deco-sites/mira-site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
